[package]
name = "ottr"
version = "0.1.0"
edition = "2021"

[lib]
name = "ottr"
path = "src/lib.rs"

[[example]]
name = "cantilever_sin_load"

[[example]]
name = "beam_mode_sweep"

[[example]]
name = "bar_urc_model_compare"

[dependencies]
approx = "0.5.1"
faer = "0.20.2"
gauss-quad = "0.2.1"
itertools = "0.13.0"
vtkio = "0.6"
